name: flashattention
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - pytest
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu124
    - torchvision --index-url https://download.pytorch.org/whl/cu124
    - triton>=2.1.0
