name: flashattention
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch>=2.0
  - pytorch-cuda>=11.8
  - numpy
  - pandas
  - pytest
  - pip
  - pip:
    - triton>=2.1.0
